---
- name: Ensure directory for apt key exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: 'https://pkgs.k8s.io/core:/stable:/v{{ kube_vagrant.kubernetes.version }}/deb/Release.key'
    keyring: '/etc/apt/keyrings/kubernetes-apt-keyring.gpg'
    state: present
  become: true

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kube_vagrant.kubernetes.version }}/deb/ /'
    filename: 'kubernetes'
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install K8s packages
  ansible.builtin.apt:
    package:
      - "kubelet={{ kube_vagrant.kubernetes.version }}*"
      - "kubeadm={{ kube_vagrant.kubernetes.version }}*"
      - "kubectl={{ kube_vagrant.kubernetes.version }}*"
    state: present
    update_cache: true
    force: yes
  retries: 2
  become: true
