---
- name: Add the Google signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  retries: 10
  become: true

- name: Add the k8s APT repo
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
  retries: 10
  become: true

- name: Install K8s packages
  apt:
    package:
      - "kubelet={{ kube_vagrant.kubernetes.version }}*"
      - "kubeadm={{ kube_vagrant.kubernetes.version }}*"
      - "kubectl={{ kube_vagrant.kubernetes.version }}*"
    state: present
    update_cache: true
    force: yes
  retries: 2
  become: true