---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Docker daemon.json file
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
  register: docker_daemon_config

- name: Restart Docker Service
  systemd:
    name: docker.service
    enabled: true
    state: restarted
  when: docker_daemon_config.changed

- name: Start Docker Service
  systemd:
    name: docker.service
    enabled: true
    state: started
  when: not docker_daemon_config.changed
