---
- name: Ensure /etc/kubernetes/pki exists
  file:
    state: directory
    path: /etc/kubernetes/pki

- name: Extract kubeadm apiserver-etcd-client files
  unarchive:
    src: "./tmp/apiserver-etcd-client-certs.tgz"
    dest: /etc/kubernetes/pki
  when: (groups['etcd']|length > 0)

- stat:
    path: /etc/kubernetes/pki/ca.key
  register: ca_key

- set_fact:
    master_kubeadm_config: |
      # Reference: https://pkg.go.dev/k8s.io/kubernetes@v1.20.5/cmd/kubeadm/app/apis/kubeadm/v1beta2
      apiVersion: kubeadm.k8s.io/v1beta2
      kind: ClusterConfiguration
      dns:
        type: CoreDNS
      {% if groups['etcd']|length > 0 %}
      etcd:
        external:
          endpoints:
      {% for item in groups['etcd'] %}
          - "https://{{ hostvars[item]['kube_vagrant']['node_info'][item]['ip'] }}:2379"
      {% endfor %}
          caFile: "/etc/kubernetes/pki/etcd/ca.crt"
          certFile: "/etc/kubernetes/pki/apiserver-etcd-client.crt"
          keyFile: "/etc/kubernetes/pki/apiserver-etcd-client.key"
      {% endif %}
      networking:
        serviceSubnet: "{{ kube_vagrant.kubernetes.kube_service_cidr | default("10.96.0.0/12") }}"
        podSubnet: "{{ kube_vagrant.kubernetes.kube_podnet_cidr | default("172.16.0.0/16") }}"
        dnsDomain: "cluster.local"
      controlPlaneEndpoint: "{{ hostvars[groups['masters'][0]]['kube_vagrant']['node_info'][groups['masters'][0]]['ip'] }}"
      apiServer:
        extraArgs:
          address: "{{ hostvars[groups['masters'][0]]['kube_vagrant']['node_info'][groups['masters'][0]]['ip'] }}"
      scheduler:
        extraArgs:
          address: "{{ hostvars[groups['masters'][0]]['kube_vagrant']['node_info'][groups['masters'][0]]['ip'] }}"
      certificatesDir: "/etc/kubernetes/pki"
      #imageRepository: "k8s.gcr.io"
      #useHyperKubeImage: false
      clusterName: "{{ kube_vagrant.kubernetes.cluster_name | default('kubernetes-vagrant') }}"

- name: Write kubeadm-config file
  copy:
    dest: /tmp/kubeadm-config.yaml
    content: "{{ master_kubeadm_config }}"

- name: Bring up master
  shell: |
    kubeadm init --config=/tmp/kubeadm-config.yaml \
                 --upload-certs \
                 --ignore-preflight-errors=NumCPU
  become: true
  when: not ca_key.stat.exists
  register: kubeadm_join

- name: .kube dir
  file: 
    path: "/home/{{ deploy_user }}/.kube"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  become: true

- name: Copy kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf 
    dest: "/home/{{ deploy_user }}/.kube/config"
    remote_src: true
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600
  become: true

- name: Copy kubeconfig locally
  fetch:
    src: /etc/kubernetes/admin.conf 
    dest: "{{ playbook_dir }}/"
    flat: true 
  become: true

- name: Get kubectl Version from CMD Line
  shell: kubectl version | base64 | tr -d '\n'
  become: true
  register: kubectl_version

- name: Dump kubeconfig to config.json
  shell: kubectl config view -o json --raw > ~/.kube/config.json
  become_user: "{{ deploy_user }}"
  become: true

- name: Read kubeconfig JSON
  shell: cat /home/{{ deploy_user }}/.kube/config.json | jq -r
  register: kubeconfigjson

- set_fact:
    kubeconfig: "{{ kubeconfigjson.stdout | from_json }}"

- set_fact:
    kubeconfig_cluster: "{{ kubeconfig.clusters[0] }}"
    kubeconfig_user: "{{ kubeconfig.users[0] }}"

- set_fact:
    kubeconfig_host: "{{ kubeconfig_cluster.cluster.server }}"
    kubeconfig_ca_cert: "{{ kubeconfig_cluster.cluster['certificate-authority-data'] }}"
    kubeconfig_client_cert: "{{ kubeconfig_user.user['client-certificate-data'] }}"
    kubeconfig_client_key: "{{ kubeconfig_user.user['client-key-data'] }}"

- name: Write CA data
  copy:
    dest: /home/{{ deploy_user }}/.kube/ca.crt
    content: "{{ kubeconfig_cluster.cluster['certificate-authority-data'] | b64decode }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600

- name: Write client cert
  copy:
    dest: /home/{{ deploy_user }}/.kube/client.crt
    content: "{{ kubeconfig_user.user['client-certificate-data'] | b64decode }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600

- name: Write client key
  copy:
    dest: /home/{{ deploy_user }}/.kube/client.key
    content: "{{ kubeconfig_user.user['client-key-data'] | b64decode }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600

- name: Untaint Master Node
  shell: kubectl taint nodes --all node-role.kubernetes.io/master- || echo "Taint already removed"
  become_user: "{{ deploy_user }}"

- name: Generate Kubectl Join Command
  shell: |
    kubeadm token create --print-join-command
  become_user: "{{ deploy_user }}"
  register: kubeadm_join_cmd

- name: "Add K8S generated join information to a dummy host"
  add_host:
    name:   "K8S_JOIN_CMD_HOLDER"
    joincmd: "{{ kubeadm_join_cmd.stdout }}"