---
- name: Configure WeaveNet (CNI)
  shell: |
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when: kube_vagrant.kubernetes.kube_cni | default("calico") == "weave" 
  become_user: "{{ deploy_user }}"