---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - debug: 
        var: ansible_default_ipv4.address

    - set_fact:
        externalIPs: "{{ externalIPs }} + [ '{{ hostvars[item]['ansible_default_ipv4']['address'] }}' ]"
      with_items: "{{ groups['all'] }}"
      vars:
        externalIPs: []

    ### Required Packages ###
    ### Import from settings.yml
    - set_fact:
        kube_vagrant: '{{ kube_vagrant | from_yaml }}'

    - include_role:
        name: "packages"

    - debug:
        var: ansible_facts.interfaces


- hosts:
    - masters
    - workers
  gather_facts: true
  become: true
  tasks:
    ### Docker Packages ###
    - include_role:
        name: "container-engine/docker"

    ### ContainerD Packages ###
    - include_role:
        name: "container-engine/containerd"

    ### Kubeadm Packages ###
    - include_role:
        name: "kubernetes/packages"

    ### Kubeadm Setup ###
    - include_role:
        name: "kubernetes/kubeadm-setup"


- hosts: masters
  gather_facts: true
  become: true
  run_once: true
  tasks:
    - include_role:
        name: "kubernetes/kubeadm-master"

    - include_role:
        name: "cni/cilium"

    - include_role:
        name: "cni/calico-tigera"


- hosts: workers
  gather_facts: true
  become: true

  tasks:
    - include_role:
        name: "kubernetes/kubeadm-worker"

- hosts: workers
  gather_facts: true

  tasks:
    - include_role:
        name: "kubernetes/kubeadm-worker"
        tasks_from: labels.yaml

- hosts: masters
  gather_facts: true

  tasks:
    - include_role:
        name: "helm-packages"

    - debug:
        msg: "NOTE: To access environment with kubectl command, run: \"export KUBECONFIG=$(pwd)/provisioning/admin.conf\""
      run_once: true