---
- hosts: all
  become: true
  tasks:
    - debug: 
        var: ansible_default_ipv4.address

    ### Required Packages ###
    ### Import from settings.yml
    - set_fact:
        kube_vagrant: '{{ kube_vagrant | from_yaml }}'

    - include_role:
        name: "packages"

- hosts:
    - masters
    - workers
    - etcd
  become: true
  tasks:
    ### Docker Packages ###
    - include_role:
        name: "container-engine/docker"

- hosts:
    - masters
    - workers
    - etcd
  become: true
  tasks:
    ### Kubeadm Packages ###
    - include_role:
        name: "kubernetes/packages"

    ### Kubeadm Setup ###
    - include_role:
        name: "kubernetes/kubeadm-setup"

- hosts:
    - etcd
  become: true
  tasks:
    ### Etcd Cluster Certificates
    - include_role:
        name: "etcd"
        tasks_from: certs.yaml

    ### Install and Setup Etcd
    - include_role:
        name: "etcd"


- hosts: masters
  become: true
  run_once: true
  tasks:
    - include_role:
        name: "kubernetes/kubeadm-master"

    - include_role:
        name: "cni/weave"

    - include_role:
        name: "cni/calico-tigera"


- hosts: workers
  become: true

  tasks:
    - include_role:
        name: "kubernetes/kubeadm-worker"

- hosts: workers

  tasks:
    - include_role:
        name: "kubernetes/kubeadm-worker"
        tasks_from: labels.yaml

- hosts: masters

  tasks:
    - include_role:
        name: "helm-packages"

    - debug:
        msg: "NOTE: To access environment with kubectl command, run: \"export KUBECONFIG=$(PWD)/provisioning/admin.conf\""
      run_once: true
