---
- name: Label worker nodes
  shell: |
    kubectl label node/{{ inventory_hostname|lower }} node-role.kubernetes.io/worker=true --overwrite=true
  connection: local
  environment:
    KUBECONFIG: "{{ playbook_dir }}/admin.conf"
  vars:
    ansible_python_interpreter: /usr/bin/python3
