---
- stat:
    path: /etc/kubernetes/pki/ca.crt
  register: ca_key

- name: "Join node with Kubectl"
  shell: |
    {{ hostvars['K8S_JOIN_CMD_HOLDER']['joincmd'] }}
  retries: 3
  when: not ca_key.stat.exists